### ISSUE TITLE
Backend: Refator rota de order

### ISSUE THREAD

**Issue by gustavofdeoliveira** [Inteli-College/2024-1B-T02-EC10-G04#63]
Mudar o retorno da rota, para ser uma lista de objetos com as informações das ordens. 

OBS: rotar com base no id do usuário recebido no JWT

**Comment by emanuelemorais** [comment]
- ID Pyxis
- Número do pedido
- Status 
- Prioridade atribuida
- Lista de remádios
- Data da solicitação
